### ISSUE TITLE
Error setting HEAD ref to 

### ISSUE THREAD

**Issue by conficient** [CurseStaff/GitSplit#2]
Trying this out on a large repo. It seems to run fine but I get an error at the end
```
Setting Branches
Setting Tags
Setting Head Refs
split-test-3: Error setting HEAD ref to
Sequence contains no elements
split-test-2: Error setting HEAD ref to
Sequence contains no elements
Converted in 00:41:17.6733943
```
My JSON file is as follows:
```json
{
  "split-test-2" :  {
        "Master" :  "split-test-2/master",
        "Branches" :  [ "split-test-2*" ],
        "Tags":  ["split-test-2*"],
        "Paths" :  [
            "Suppliers\\Suppliers.sln",
            "Suppliers\\QuoteTestWeb\\*",
            "Suppliers\\QuoteTestWeb.Tests\\*"
        ]
    },
    // Create a new repository named split-test-3
    // Import the Curse.split-test-3.sln file, and all files and directories under Source\Curse.split-test-3, Source\Curse.split-test-3.Foo, and Source\Curse.split-test-3.Bar
    // Set any tag beginning with split-test-3
    // Set any branch beginning with split-test-3
    // Set the master branch to point to the branch split-test-3/master
    "split-test-3" :  {
        "Master" :  "split-test-3/master",
        "Branches" :  [ "split-test-3*" ],
        "Tags":  ["split-test-3*"],
        "Paths" :  [
            "Suppliers\\Suppliers.sln",
            "Suppliers\\Anvil.Energy\\*",
            "Suppliers\\Anvil.Energy.Tests\\*"
        ]
    }
}
```

**Comment by cpaul747** [comment]
What branches do you have in the original repo?  Did you do the bare/mirror checkout to pull everything down before running the tool?  This should only happen if there's no branches that match the wildcard in the source repo.

That said, setting the head ref is the last step in the tool, and can be done on the git command line.  See https://git-scm.com/docs/git-update-ref

**Comment by conficient** [comment]
Ah, I missed the bit about the source being a _bare_ git repository. I'll try that and update, thanks

**Comment by conficient** [comment]
Ok, did a `git clone --bare` and re-ran - had the same error as before.

Tried to find anything in the bare output repos - tried converting to regular ones and can't find anything so I guess this is either too complicated for me or it's broken. Thanks anyway.
